version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./Frontend and UI:/usr/share/nginx/html:ro
