services:
  - type: web
    name: backSme
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/src/app.js
    envVarGroups:
      - name: EcoSME
