CREATE TABLE IF NOT EXISTS public.esg_metrics (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid,
    month text,
    spoilage_prevented_bdt real,
    plastic_offset_kg real,
    carbon_sequestered_kg real,
    water_saved_l real,
    waste_reduced_kg real,
    e_score real,
    s_score real,
    g_score real,
    esg_score real,
    trust_score real,
    dvs_score real,
    CONSTRAINT esg_metrics_pkey PRIMARY KEY (id)
);
